server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: uniplat-api

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:uniplat}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}

database-heroku:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:uniplat}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
