server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: uniplat-api
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
      ACCEPT_FLOAT_AS_INT: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: uniplat1010@gmail.com
    password: Bitirme.123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:uniplat}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}
  connectionPool:
    maxSize: ${MAX_POOL_SIZE:10}
    initialSize: ${INITIAL_POOL_SIZE:5}
    maxIdleTime: ${MAX_IDLE_TIME:PT30M}
    maxCreateConnectionTime: ${MAX_CREATE_CONNECTION_TIME:PT5S}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

api:
  file-api:
    baseUrl: ${FILE_API_BASE_URL:http://localhost:9000}
    connectionTimeout: PT5S
    readTimeout: PT30S
    memorySizeByMB: 5
