server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: uniplat-api

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:uniplat}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

api:
  file-api:
    baseUrl: ${FILE_API_BASE_URL:http://localhost:9000}
    connectionTimeout: PT5S
    readTimeout: PT30S
